const {sql}=require('@vercel/postgres');
const crypto=require('crypto');
const bcrypt=require('bcryptjs');

async function initDb(){
  await sql`CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, role TEXT NOT NULL DEFAULT 'user', balance BIGINT NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS vps_stock (id SERIAL PRIMARY KEY, ip TEXT NOT NULL, username TEXT NOT NULL, ssh_port INTEGER NOT NULL DEFAULT 22, password_cipher TEXT NOT NULL, price BIGINT NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'available', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
  await sql`CREATE TABLE IF NOT EXISTS deposits (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, provider_id TEXT UNIQUE NOT NULL, amount BIGINT NOT NULL, received BIGINT NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'pending', credited_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), expired_at TIMESTAMPTZ)`;
  await sql`CREATE TABLE IF NOT EXISTS otp_orders (id SERIAL PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, upstream_order_id TEXT UNIQUE, number_id BIGINT NOT NULL, provider_id TEXT NOT NULL, operator_id BIGINT NOT NULL, service_id BIGINT, country TEXT, phone_number TEXT, price BIGINT NOT NULL, status TEXT NOT NULL DEFAULT 'processing', refunded_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
}
function secret32(name){const raw=process.env[name];if(!raw)throw new Error(`${name} is not configured`);return crypto.createHash('sha256').update(raw).digest()}
function enc(s){const iv=crypto.randomBytes(12);const c=crypto.createCipheriv('aes-256-gcm',secret32('VPS_CRYPT_KEY'),iv);const out=Buffer.concat([c.update(String(s),'utf8'),c.final()]);return `${iv.toString('base64url')}.${c.getAuthTag().toString('base64url')}.${out.toString('base64url')}`}
function dec(s){const [iv,tag,data]=String(s).split('.');const d=crypto.createDecipheriv('aes-256-gcm',secret32('VPS_CRYPT_KEY'),Buffer.from(iv,'base64url'));d.setAuthTag(Buffer.from(tag,'base64url'));return Buffer.concat([d.update(Buffer.from(data,'base64url')),d.final()]).toString('utf8')}
function parseCookies(req){return Object.fromEntries(String(req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}))}
function setCookie(res,name,value,maxAge){const secure=process.env.COOKIE_SECURE!=='false'?'; Secure':'';res.setHeader('Set-Cookie',`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${secure}`)}
async function createSession(userId){const id=crypto.randomBytes(32).toString('hex');await sql`INSERT INTO sessions(id,user_id,expires_at) VALUES(${id},${userId},NOW()+INTERVAL '7 days')`;return id}
async function requireSession(req){const sid=parseCookies(req).zxv_session;if(!sid)return null;const {rows}=await sql`SELECT u.id,u.username,u.role,u.balance,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=${sid} AND s.expires_at>NOW() AND u.active=TRUE LIMIT 1`;return rows[0]||null}
async function logout(req,res){const sid=parseCookies(req).zxv_session;if(sid)await sql`DELETE FROM sessions WHERE id=${sid}`;setCookie(res,'zxv_session','',0)}
function verifyStoredPassword(password,stored){const v=String(stored||'');if(/^\$2[aby]\$/.test(v))return bcrypt.compare(password,v);if(!v.startsWith('pbkdf2_sha256$'))return false;const [,algo,iters,saltHex,digestHex]=v.split('$');if(algo!=='pbkdf2_sha256'||!/^[0-9]+$/.test(iters)||!/^[0-9a-f]+$/i.test(saltHex)||!/^[0-9a-f]+$/i.test(digestHex))return false;const actual=crypto.pbkdf2Sync(String(password),Buffer.from(saltHex,'hex'),Number(iters),32,'sha256');const expected=Buffer.from(digestHex,'hex');return expected.length===actual.length&&crypto.timingSafeEqual(actual,expected)}
async function githubUsers(){const repo=process.env.GITHUB_REPO||'NanoXyinDev/Zxv-Order',path=process.env.GITHUB_USERS_PATH||'users.json',branch=process.env.GITHUB_BRANCH||'main',token=process.env.GITHUB_TOKEN;if(!token)throw new Error('GITHUB_TOKEN is not configured');const url=`https://api.github.com/repos/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`;const r=await fetch(url,{headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ZxvCode-Store'}});if(!r.ok)throw new Error(`GitHub users.json request failed (${r.status})`);const file=await r.json();const raw=Buffer.from(file.content.replace(/\n/g,''),'base64').toString('utf8');const json=JSON.parse(raw);return {users:Array.isArray(json)?json:(Array.isArray(json.users)?json.users:[]),sha:file.sha,repo,path,branch}}
async function githubWriteUsers(users,sha,message){const repo=process.env.GITHUB_REPO||'NanoXyinDev/Zxv-Order',path=process.env.GITHUB_USERS_PATH||'users.json',branch=process.env.GITHUB_BRANCH||'main',token=process.env.GITHUB_TOKEN;if(!token)throw new Error('GITHUB_TOKEN is not configured');const url=`https://api.github.com/repos/${repo}/contents/${path}`;const content=Buffer.from(JSON.stringify({users},null,2)+'\n').toString('base64');const r=await fetch(url,{method:'PUT',headers:{Authorization:`Bearer ${token}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'ZxvCode-Store','Content-Type':'application/json'},body:JSON.stringify({message,content,sha,branch})});if(!r.ok){const t=await r.text();throw new Error(`GitHub users.json write failed (${r.status}) ${t.slice(0,160)}`)}return r.json()}
async function ensureUserRecord(u){const username=String(u.username);const {rows}=await sql`INSERT INTO users(username,role,active) VALUES(${username},${u.role||'user'},${u.active!==false}) ON CONFLICT(username) DO UPDATE SET role=EXCLUDED.role,active=EXCLUDED.active,updated_at=NOW() RETURNING id,username,role,balance,active`;return rows[0]}
async function userBySession(req){await initDb();return requireSession(req)}
module.exports={sql,initDb,enc,dec,bcrypt,createSession,requireSession,logout,setCookie,verifyStoredPassword,githubUsers,githubWriteUsers,ensureUserRecord,userBySession};
